### ISSUE TITLE
Seems MNIST got very low acc in test data?

### ISSUE THREAD

**Issue by xuehui1991** [chentingpc/gfn#1]
Here is the mnist result  in "image-gcn" mode from the source code:

![image](https://user-images.githubusercontent.com/6280746/60650746-54a66a80-9e77-11e9-95a9-291b9aba129c.png)

It seems MNIST got very low acc in test data and I cannot reproduce the number in paper.

Do you have any comments or suggestion?
Thank you.

**Comment by chentingpc** [comment]
Thanks for reporting this issue. 

To run image dataset, you will need to change some default parameters. You can run with the following command in order to get the correct result:

`python main.py --exp image_gcn --with_eval_mode False --res_branch resnet --epochs 50`

Hope that helps.

**Comment by xuehui1991** [comment]
@chentingpc  Thank you~ I will ping you if I have other questions.

**Comment by xuehui1991** [comment]
The CIFAR10 result which network is "Res_Conv7_fc2" is lower than many STOA result. @chentingpc  Do you have any comments about that?  Thank you.

**Comment by chentingpc** [comment]
The GCN differs from CNN in that it does not distinguish filters from
different orientations. In other words, a graph conv operation at a
specific pixel location would use same filter/kernel for all neighbors in
the same way. This limits the model expressiveness for detecting more
sophisticated patterns (such as in CIFAR10).

Best,
Ting

**Comment by xuehui1991** [comment]
Thank you @chentingpc . I agree with you about " a graph conv operation at a specific pixel location would use same filter/kernel for all neighbors in the same way".

Another question in my mind is, "For context, when using coordinates as features both GCN and GFN
achieves nearly 99% accuracy"  mentioned in your paper. What's that "using coordinates as features" method means?

.The network "Res_Conv5_dc2" got 95% acc in Mnist dataset, so how could I "using coordinates as feature to get 99% acc"? 

Thank you.

**Comment by chentingpc** [comment]
To run with coordinate features, you can add "+coord" to feat_str, which enables it in here: https://github.com/chentingpc/gfn/blob/8854d10a40d583e3adfa30a759f4eff757b8b5d3/datasets.py#L28
