### ISSUE TITLE
Error running gfn on torch_geometric version newest version 1.3.2

### ISSUE THREAD

**Issue by richardmark** [chentingpc/gfn#4]
The train_eval.py file now causes an error - tensors used as indices must be long or byte tensors when used in latest version of torch_geometric version 1.3.2. This can be fixed by adding .long() to the  test_indices[i] and  val_indices[i] before train_mask is called.

        test_indices[i] = test_indices[i].long()
        val_indices[i] = val_indices[i].long()
        train_mask[test_indices[i]] = 0
        train_mask[val_indices[i]] = 0

I have not found any other errors after the upgrade to torch_geometric version 1.3.2.

**Comment by chentingpc** [comment]
Hi, Thanks for providing reporting the issue (and solution)! Do you want to create a pull request on this?

**Comment by richardmark** [comment]
Thank,
Yes please.
Rick

**Comment by chentingpc** [comment]
Did you create a pull request? I didn't see one. Here is a guide if you want: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by chentingpc** [comment]
fixed in https://github.com/chentingpc/gfn/commit/9cf9e76eedeafeafcb7840334199baed6027848a
