### ISSUE TITLE
dataset processed problem

### ISSUE THREAD

**Issue by LvShengZe903** [chentingpc/gfn#5]
When I run this code, exist a problem that there is no file named data_deg+odeg100+ak3+reall.pt.
![image](https://user-images.githubusercontent.com/51954425/86510264-cfa2b800-be20-11ea-8a98-b80b694b3bd8.png)
I'd appreciate it for your early reply.

**Comment by chentingpc** [comment]
did you set the `root` to an existing folder?

https://github.com/chentingpc/gfn/blob/693db48381f21a6c2a276e9147ec30008fcb0aaf/datasets.py#L13

Also, which version of pytorch_geometric are you using?

**Comment by LvShengZe903** [comment]
> did you set the `root` to an existing folder?
> 
> https://github.com/chentingpc/gfn/blob/693db48381f21a6c2a276e9147ec30008fcb0aaf/datasets.py#L13
> 
> Also, which version of pytorch_geometric are you using?

Thanks for your early reply. There is no .pt file in the folder. I download the dataset but only have the row file. I want to know how the .pt file exist from row dataset and my pytorch_geometric version is 1.5.0.

**Comment by chentingpc** [comment]
These files should be created automatically. If this doesn't work it is likely due to pytorch_geometric 1.5.0. I suggest you either try pytorch_geometric 1.0, or use a root directory has no data there (see if the data got automatically downloaded and parsed).

**Comment by LvShengZe903** [comment]
> These files should be created automatically. If this doesn't work it is likely due to pytorch_geometric 1.5.0. I suggest you either try pytorch_geometric 1.0, or use a root directory has no data there (see if the data got automatically downloaded and parsed).

I am really appreciate for your reply. Thank you very much.
