### ISSUE TITLE
Code can't run

### ISSUE THREAD

**Issue by wangzeyu135798** [chentingpc/gfn#7]
When I run this code "python main.py --exp benchmark"
Some errors report， No such file or directory: 'data/MUTAG/MUTAG/processed/data_deg+odeg100+ak3+reall.pt'

**Comment by chentingpc** [comment]
please check your environment setup. feel free to post your solution here if found.

**Comment by wangzeyu135798** [comment]
Thanks for your respond. I want to learn the exact environment in this project. I use torch-geometric(1.1.0 version) instead of original 1.6.0 version while there is still another error.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chentingpc/gfn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月4日(星期天) 晚上7:41
收件人:&nbsp;"chentingpc/gfn"<gfn@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chentingpc/gfn] Code can't run (#7)





 
please check your environment setup. feel free to post your solution here if found.
